<?php /** @var $block Mycompany\Message\Block\MessageForm */ ?>

<?php $form = $block->getMessageForm(); ?>

<form action="" method="post">
    Title : <input type="text" name="title" value="<?php echo $form ? $form->getTitle() : null; ?>" /><br />
    Content : <input type="text" name="content" value="<?php echo $form ? $form->getContent() : null; ?>" /><br/>
    <br/>
    <input type="submit"/>
</form>

<br />
<a href="<?php echo $block->getUrl('*/*/index'); ?>">Retour<a>
